# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-eventsview-controls-remastered-patch

# >> macros
BuildArch: armv7hl
# << macros

Summary:    Eventsview controls patch with settings
Version:    0.0.12
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   lipstick-jolla-home-qt5 >= 0.23.20.11
Conflicts:  sailfishos-eventsview-controls-1row-volume-patch
Obsoletes:  sailfishos-eventsview-controls-1row-volume-patch

%description
Remastered Eventsview controls patch you can configure using Eventsview
 controls settings applet.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-eventsview-controls-remastered-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-eventsview-controls-remastered-patch
mkdir -p %{buildroot}/usr/share/jolla-settings/pages/sailfishos-eventsview-controls-remastered-patch
cp -r settings/*.qml %{buildroot}/usr/share/jolla-settings/pages/sailfishos-eventsview-controls-remastered-patch
mkdir -p %{buildroot}/usr/share/jolla-settings/entries
cp -r settings/*.json %{buildroot}/usr/share/jolla-settings/entries/
# << install pre

# >> install post
# << install post

%pre
# >> pre
/usr/sbin/patchmanager -u sailfishos-eventsview-controls-remastered-patch
# << pre

%preun
# >> preun
/usr/sbin/patchmanager -u sailfishos-eventsview-controls-remastered-patch
# << preun

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-eventsview-controls-remastered-patch
%{_datadir}/jolla-settings/entries
%{_datadir}/jolla-settings/pages
# >> files
# << files
